version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql:/var/lib/mysql
        tty: true
        command: --innodb-use-native-aio=0
        restart: always
        
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"